on:
  release:
    types: [published]

name: Build and Release

jobs:
  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build macOS app
        run: ./build.sh ${{ github.event.release.tag_name }}

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacServerMonitor-macOS
          path: build/MacServerMonitor-${{ github.event.release.tag_name }}.zip

  upload:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: [build-macos]
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: List downloaded files
        run: ls -R

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: MacServerMonitor-macOS/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
